version: '3.9'

services:
  auth-service:
    build: ./apps/auth-service
    ports:
      - "5000:5000"
    env_file:
      - ./apps/auth-service/.env
    depends_on:
      - postgres
    restart: always
  user-service:
    build: ./apps/user-service
    ports:
      - "5001:5001"
    env_file:
      - ./apps/user-service/.env
    depends_on:
      - postgres
    restart: always  

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: edubidpro_auth
      POSTGRES_USER: edubid_user
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
